urls.py
from django.conf.urls.defaults import *
from campenport.views import homemap, buildinglist, search, comparebuildings, campus, versus, robots, versus2
from campenport.contact.views import contact, contactThanks, contact2
import campenport.settings as settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	(r'^$', 'campenport.views.passhome'),
	(r'^map/$', homemap),
	(r'^api/$', include('campenport.api.urls')),
	(r'^buildlist/$', buildinglist),
	(r'^compare/$', comparebuildings),
	(r'^campus/$', campus),
	(r'^buildings/(?P<buildname>[a-zA-Z0-9_.-]+)/$', 'campenport.buildings.views.buildings'),
	(r'^versus/(?P<buildname1>[a-zA-Z0-9_.-]+)/(?P<buildname2>[a-zA-Z0-9_.-]+)/$', versus2),
	(r'^search/$', search),
	(r'^versus/$', versus),
	(r'^ARDgetData/', include('campenport.ARDgetData.urls')),
	(r'^site-media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.SITE_MEDIA + '/site-media/'}),
	(r'^admin/', include(admin.site.urls)),
	(r'^robots.txt', robots),
	(r'contact/thanks/', contactThanks),
	(r'^contact/in/(?P<buildnameC>[a-zA-Z0-9_.-]+)/$', contact),
	(r'^contact/in/', contact2),
)

contact/models.py
from django.db import models

# Create your models here.

class ContactResp(models.Model):
	suggestion = models.TextField()
	emailID = models.EmailField(blank=True)
	rBuilding = models.CharField(max_length=100)
	time = models.DateTimeField(auto_now_add=True)
	
	

contact/forms.py
from django.forms import ModelForm
from campenport.contact.models import ContactResp

class ContactForm(ModelForm):
	class Meta:
		model = ContactResp
    

contact/views.py
# Create your views here.

from django.shortcuts import render_to_response
from campenport.contact.forms import ContactForm
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from campenport.buildings.models import Building

def contact(request, buildnameC):
    if buildnameC=="General Site":
        building_name_in = "General Site"
    else:
        correctbuilding = Building.objects.filter(shortname=buildnameC)
        building_name_in = correctbuilding[0].longname
    buildings = Building.objects.all()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm()
    return render_to_response('contact_form.html', locals())

def contact2(request):
	return contact(request, "General Site")

def contactThanks(request):
	buildings = Building.objects.all()
	return render_to_response('contact_thanks.html', locals())

contact/templates/contact_form.html
{% extends "sitebase.html" %}
{% block title %}Submit a Suggestion{% endblock %}
{% block header_title %}Submit a Suggestion:{% endblock %}
{% block content_inside %}
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
		<div style="min-height:250px;">
			<div id="leftbar" style="float:left;">
				<div><legend><h3>Your Email Address (optional):</h3></legend><input id="id_emailID" type="text" name="emailID" maxlength="75" /></div><br>
				<div><legend><h3>Relevant Building:</h3></legend><input id="id_rBuilding" type="text" name="rBuilding" maxlength="100" value="{{ building_name_in }}" /></div>
			</div>
			<div id="rightbar" style="float:right;">
				<div><legend><h3>Your Suggestion: </h3></legend>&nbsp;&nbsp;<textarea class="xxlarge" id="id_suggestion" rows="5" cols="50" name="suggestion" style="float:right;"></textarea></div></div>
			</div>

			<div><br>
				<input type="submit" class="btn primary" value="Submit Your Suggestion"> *We'll do our best to respond.
			</div>
    </form>
{% endblock %}

contact/templates/contact_thanks.html
{% extends "sitebase.html" %}
{% block title %}Thanks!{% endblock %}
{% block header_title %}
Thanks for Submitting Your Suggestion!
{% endblock %}
{% block content_inside %}
<h3>If you gave an email address we'll try to respond to your suggestion.</h3>
Return <a href="/">Home</a>
{% endblock %}